function webfonts(){var N='bootstrap',O='begin',P='gwt.codesvr.webfonts=',Q='gwt.codesvr=',R='webfonts',S='startup',T='DUMMY',U=0,V=1,W='iframe',X='javascript:""',Y='position:absolute; width:0; height:0; border:none; left: -1000px;',Z=' top: -1000px;',$='CSS1Compat',_='<!doctype html>',ab='',bb='<html><head><\/head><body><\/body><\/html>',cb='undefined',db=/loaded|complete/,eb='DOMContentLoaded',fb=50,gb='Chrome',hb='eval("',ib='");',jb='script',kb='javascript',lb='moduleStartup',mb='moduleRequested',nb='head',ob='meta',pb='name',qb='webfonts::',rb='::',sb='gwt:property',tb='content',ub='=',vb='gwt:onPropertyErrorFn',wb='Bad handler "',xb='" for "gwt:onPropertyErrorFn"',yb='gwt:onLoadErrorFn',zb='" for "gwt:onLoadErrorFn"',Ab='#',Bb='?',Cb='/',Db=/^\w+:\/\//,Eb='img',Fb='clear.cache.gif',Gb='baseUrl',Hb='webfonts.nocache.js',Ib='base',Jb='//',Kb=/^\//,Lb=/^[a-zA-Z]+:\/\//,Mb='user.agent',Nb='webkit',Ob='safari',Pb='msie',Qb=10,Rb='ie10',Sb=9,Tb='ie9',Ub=8,Vb='ie8',Wb='gecko',Xb='gecko1_8',Yb='unknown',Zb=2,$b=3,_b=4,ac='selectingPermutation',bc='webfonts.devmode.js',cc='5DB0853C43930AF2E639741A0581722D',dc='9B835EEACD2C1BC356454445A1F2CE7A',ec='C39119EC55DB7C482616478E4F540D25',fc='E7045E5CEAB85AE45BD31EEFA29827F1',gc='FC742334F31AF6767D5BBDC45F5EACA9',hc=':',ic='.cache.js',jc='loadExternalRefs',kc='end',lc='http:',mc='file:',nc='_gwt_dummy_',oc='__gwtDevModeHook:webfonts',pc=/^https?:\/\/(localhost|[a-zA-Z0-9.-]+\.(corp|prod)\.google\.com):[0-9]+\/.*$/,qc='Ignoring non-whitelisted Dev Mode URL: ',rc=':moduleBase';var o=window;var p=document;r(N,O);function q(){var a=o.location.search;return a.indexOf(P)!=-1||a.indexOf(Q)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:R,sessionId:o.__gwtStatsSessionId,subSystem:S,evtGroup:a,millis:(new Date).getTime(),type:b})}}
webfonts.__sendStats=r;webfonts.__moduleName=R;webfonts.__errFn=null;webfonts.__moduleBase=T;webfonts.__softPermutationId=U;webfonts.__computePropValue=null;webfonts.__getPropMap=null;webfonts.__installRunAsyncCode=function(){};webfonts.__gwtStartLoadingFragment=function(){return null};webfonts.__gwt_isKnownPropertyValue=function(){return false};webfonts.__gwt_getMetaProperty=function(){return null};__propertyErrorFunction=null;var s=o.__gwt_activeModules=o.__gwt_activeModules||{};s[R]={moduleName:R};webfonts.__moduleStartupDone=function(e){var f=s[R].bindings;s[R].bindings=function(){var a=f?f():{};var b=e[webfonts.__softPermutationId];for(var c=U;c<b.length;c++){var d=b[c];a[d[U]]=d[V]}return a}};var t;function u(){v();return t}
function v(){if(t){return}var a=p.createElement(W);a.src=X;a.id=R;a.style.cssText=Y+Z;a.tabIndex=-1;p.body.appendChild(a);t=a.contentDocument;if(!t){t=a.contentWindow.document}t.open();var b=document.compatMode==$?_:ab;t.write(b+bb);t.close()}
function w(k){function l(a){function b(){if(typeof p.readyState==cb){return typeof p.body!=cb&&p.body!=null}return db.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(eb,d,false)}var e=setInterval(function(){if(b()){d()}},fb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=u();var f=e.body;var g;if(navigator.userAgent.indexOf(gb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(hb));for(var i=U;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(V,j.length-V)))}h.appendChild(e.createTextNode(ib));g=e.createElement(jb);g.language=kb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=U;i<c.length;i++){g=e.createElement(jb);g.language=kb;g.text=c[i];f.appendChild(g);d(f,g)}}}
webfonts.onScriptDownloaded=function(a){l(function(){m(a)})};r(lb,mb);var n=p.createElement(jb);n.src=k;p.getElementsByTagName(nb)[U].appendChild(n)}
webfonts.__startLoadingFragment=function(a){return C(a)};webfonts.__installRunAsyncCode=function(a){var b=u();var c=b.body;var d=b.createElement(jb);d.language=kb;d.text=a;c.appendChild(d);c.removeChild(d)};function A(){var c={};var d;var e;var f=p.getElementsByTagName(ob);for(var g=U,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(pb),k;if(j){j=j.replace(qb,ab);if(j.indexOf(rb)>=U){continue}if(j==sb){k=i.getAttribute(tb);if(k){var l,m=k.indexOf(ub);if(m>=U){j=k.substring(U,m);l=k.substring(m+V)}else{j=k;l=ab}c[j]=l}}else if(j==vb){k=i.getAttribute(tb);if(k){try{d=eval(k)}catch(a){alert(wb+k+xb)}}}else if(j==yb){k=i.getAttribute(tb);if(k){try{e=eval(k)}catch(a){alert(wb+k+zb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;webfonts.__errFn=e}
function B(){function e(a){var b=a.lastIndexOf(Ab);if(b==-1){b=a.length}var c=a.indexOf(Bb);if(c==-1){c=a.length}var d=a.lastIndexOf(Cb,Math.min(c,b));return d>=U?a.substring(U,d+V):ab}
function f(a){if(a.match(Db)){}else{var b=p.createElement(Eb);b.src=a+Fb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Gb);if(a!=null){return a}return ab}
function h(){var a=p.getElementsByTagName(jb);for(var b=U;b<a.length;++b){if(a[b].src.indexOf(Hb)!=-1){return e(a[b].src)}}return ab}
function i(){var a=p.getElementsByTagName(Ib);if(a.length>U){return a[a.length-V].href}return ab}
function j(){var a=p.location;return a.href==a.protocol+Jb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==ab){k=h()}if(k==ab){k=i()}if(k==ab&&j()){k=e(p.location.href)}k=f(k);return k}
function C(a){if(a.match(Kb)){return a}if(a.match(Lb)){return a}return webfonts.__moduleBase+a}
function D(){var f=[];var g=U;function h(a,b){var c=f;for(var d=U,e=a.length-V;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
j[Mb]=function(){var a=navigator.userAgent.toLowerCase();if(function(){return a.indexOf(Nb)!=-1}())return Ob;if(function(){return a.indexOf(Pb)!=-1&&p.documentMode==Qb}())return Rb;if(function(){return a.indexOf(Pb)!=-1&&p.documentMode>=Sb}())return Tb;if(function(){return a.indexOf(Pb)!=-1&&p.documentMode>=Ub}())return Vb;if(function(){return a.indexOf(Wb)!=-1}())return Xb;return Yb};i[Mb]={gecko1_8:U,ie10:V,ie8:Zb,ie9:$b,safari:_b};__gwt_isKnownPropertyValue=function(a,b){return b in i[a]};webfonts.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};webfonts.__computePropValue=k;o.__gwt_activeModules[R].bindings=webfonts.__getPropMap;r(N,ac);if(q()){return C(bc)}var l;try{h([Rb],cc);h([Xb],dc);h([Vb],ec);h([Tb],fc);h([Ob],gc);l=f[k(Mb)];var m=l.indexOf(hc);if(m!=-1){g=parseInt(l.substring(m+V),Qb);l=l.substring(U,m)}}catch(a){}webfonts.__softPermutationId=g;return C(l+ic)}
function F(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(jc,O);r(jc,kc)}
A();webfonts.__moduleBase=B();s[R].moduleBase=webfonts.__moduleBase;var G=D();if(o){var H=!!(o.location.protocol==lc||o.location.protocol==mc);o.__gwt_activeModules[R].canRedirect=H;function I(){var b=nc;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(H&&I()){var J=oc;var K=o.sessionStorage[J];if(!pc.test(K)){if(K&&(window.console&&console.log)){console.log(qc+K)}K=ab}if(K&&!o[J]){o[J]=true;o[J+rc]=B();var L=p.createElement(jb);L.src=K;var M=p.getElementsByTagName(nb)[U];M.insertBefore(L,M.firstElementChild||M.children[U]);return false}}}F();r(N,kc);w(G);return true}
webfonts.succeeded=webfonts();